version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: Europe/Berlin
    reviewers:
      - hassan715
    labels:
      - "Type: CI"
      - "Type: Dependencies"

  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: Europe/Berlin
    ignore:
      - dependency-name: "prettier"
        versions: [">1.14.3"]
    reviewers:
      - hassan715
    labels:
      - "Type: Dependencies"
    versioning-strategy: increase
    rebase-strategy: disabled
