blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/:vendor_name/:package_name/discussions/new?category=q-a
    about: Ask the community for help here.
  - name: Report a bug
    url: https://github.com/:vendor_name/:package_name/issues/new
    about: Report a reproducable bug here.
